### ISSUE TITLE
Playground bug

### ISSUE THREAD

**Issue by GiladKingsley** [4skinSkywalker/Syllogimous-v4#11]
The playground completes syllogimous v4 into a true and full upgrade from v3.

I noticed a bug where it shows a blank screen when I tried to play only syllogisms with analogy and binary and maximum premises.
It went completely blank and upon refresh, it showed Timeout.

Additionally, I do not think playground wins and losses should affect the player’s rank.

**Comment by 4skinSkywalker** [comment]
Bug should be fixed! It was a bug due to bad validation when you play analogy or binary you need two other kinds of basic questions. Soon I'll bundle for deploy, reopen this if it's not fixed, thanks
