### ISSUE TITLE
Adaptive & advanced timer options

### ISSUE THREAD

**Issue by GiladKingsley** [4skinSkywalker/Syllogimous-v4#2]
## Background & Motivation
In relational frame training studies, we commonly see high drop-out rates, likely because these exercises can be tough and frustrating. While we want to maintain the cognitive challenge these exercises provide, we can implement adaptive systems to help users progress through the difficulty curve. The features suggested below aim to reduce early-stage frustration while preserving the training's effectiveness and allowing for increased difficulty in high-performance areas.

# Game Modes for Syllogimous

## Start Screen
Add a three-way toggle next to "Press to Play":
- Normal (no timer): For learning and practice without pressure
- Timer (fixed time limits): For the normal challenge
- Smart Timer (automated adjustment): For personalized progression

## Stats Section
- Toggle to switch between viewing stats for each mode
- Shows stats matching your current play mode by default
- Visual feedback on progress and improvement

## Timer Controls (in Stats)
- Input field for time per problem type
- Reset to default option
- These controls are grayed out when in Smart Timer mode
- Adjustable target timeout rate for Smart Timer (default 15%)

## Smart Timer Algorithm
- Automatically adjusts time limits to achieve the target timeout rate
- Tracks and adjusts separately per problem category to prevent frustration clustering in challenging areas
- Maintains rolling window of maximum 30 rounds per problem type
- During initial data gathering (before reaching 30 rounds):
  • Calculates timeout rate using all available data points so far
  • Triggers immediate time increase if 3 consecutive timeouts occur
  • Dynamically adjusts based on current window size
- Once 30 rounds are reached, maintains rolling window and adjusts based on full window
- Ensures smooth progression from beginner to advanced levels
- After each difficulty level increase, increase timer length by a similar ratio to the time increase in the default mode

## Progress Tracking
- Maintain separate level systems for each mode (Adept-Transcendent, consider asking an LLM for 24 new adjectives for these)
- Provides clear sense of advancement across different play styles
- Allows users to track improvement across multiple approaches

**Comment by 4skinSkywalker** [comment]
![image](https://github.com/user-attachments/assets/9c41d6e5-d054-4d58-b7ef-c594d1e54dc2)
New adaptive algo, it should adapt better.

I've also added the fixed timer based on tier by I need a hand in making a good timer for each tier and question type. Could you help me? :D

**Comment by GiladKingsley** [comment]
I'm yet to have a great idea on how to set the times for the fixed timer

**Comment by 4skinSkywalker** [comment]
I've removed the tiered timer, now there's one custom and one adaptive
