### ISSUE TITLE
Adaptive Time-Based Question Selection & Per-Type Difficulty System

### ISSUE THREAD

**Issue by GiladKingsley** [4skinSkywalker/Syllogimous-v4#7]
# Adaptive Time Distribution and Per-Type Difficulty System

### Problem Statement
Currently, different types of questions can require varying amounts of time to solve, even when they contain the same number of premises. This leads to uneven practice distribution, as users spend more time on certain types regardless of their intended focus. The system should account for these natural differences in solving times and allow users to control how they distribute their practice time across different question types.

---

### Proposed Solution
The solution consists of two main components that work together to create a more balanced and customizable practice experience.

#### 1. Time-Based Question Selection
The core of this system is intelligent question type selection based on user-defined time distribution targets. Instead of treating all question types equally, the system tracks solving times for each type at different difficulty levels. Using a sigmoid-weighted moving average that favors recent performance, the system maintains accurate estimates of how long each type of question takes for the user to solve.

The selection algorithm then uses these time estimates along with user-defined targets to choose which type of question to present next. If a user wants to spend equal time on two types, but one typically takes twice as long to solve, the faster type will be selected more frequently to achieve the desired time balance.

#### 2. Per-Type Difficulty Progression
While maintaining the global tier system for unlocking new question types, each type will have its own difficulty progression. This allows users to advance at different rates in different areas while ensuring they experience all question types. The per-type point system will be simplified to have equal gains and losses across all types, unlike the current gain/loss asymmetry in the global tier up to 2400 pts at Prodigy (gaining 10 pts and losing 5).

---

### Settings and Controls
A new settings interface will allow users to specify their desired time distribution using interdependent sliders. When adjusting one slider, others automatically adjust to maintain a total of 100%. The interface will also display current time distribution statistics and allow users to toggle optional features like N-Back style difficulty adaptation.

#### Additional Benefits
Per-Type Difficulty Progression solves an additional issue where users can be pushed into higher tiers, such as the 2400-point range, even if they are struggling. This can place them in difficulty levels that exceed their skill, forcing them to confront overly challenging questions. As a result, users can become overwhelmed, lose motivation, and eventually abandon the game.

The per-type difficulty progression addresses this by allowing users to progress independently in each question type, ensuring they only face questions appropriate for their skill level. This tailored approach prevents users from being prematurely exposed to advanced content, helping them stay engaged and build confidence at a manageable pace.

**Comment by 4skinSkywalker** [comment]
You wrote "If a user wants to spend equal time on two types, but one typically takes twice as long to solve, the faster type will be selected more frequently to achieve the desired time balance." but that doesn't make much sense to me, for two reasons:
1. A chain is as strong as the weakest link and the slowest questions are usually the ones in which you are weaker;
2. You won't get as fast on questions you don't see as often.

By the way I'm playing these days and with the new adjustments in the adaptive timer I'm doing fine, I'm progressing and the time is almost always enough despite being pushy (which I guess it's the point of all of it).

**Comment by GiladKingsley** [comment]
This is mainly because the current equating of questions based on type and premise count feels either arbitrary or based on too low a sample size.
For instance, how do we accurately and definitively decide that a 6-premise direction 3d question should take as long as, or should be as difficult as a 6-premise comparison numerical question?
The combination of the difficulty adjustment per question type, and question type selection based on time, ensures that the player practices all types about equally as long, and quickly reaches a point where all question types take about as long as each other per question. They will still practice their 'weeker' areas, it will just not overwhelm the others.
We are balancing the difficulty distribution across all types to hopefully ideal levels.
This feels right.

"You won't get as fast on questions you don't see as often." - you will practice the 'weaker' areas just as long, the time will be equated.
You can think of it as not reducing the time or difficulty of the difficult questions but rather shining some light on the easier questions that you solve much faster.

The adjustment of target time proportions beyond the default of equal proportions, is a nice bonus for if a player wants to focus on specifics but still wants the ease of use and seamlessness of the normal mode compared to the playground.
This is also good for if a player has a theory they want to check that suggests different setups are superior, or if they want to mimic the relational frame contents found in other relational frame training programs described in the literature.

**Comment by 4skinSkywalker** [comment]
I'm rejecting this because it's not clear to me if that's advantageous
