### ISSUE TITLE
Stats addition

### ISSUE THREAD

**Issue by GiladKingsley** [4skinSkywalker/Syllogimous-v4#9]
# Stats addition

---

* Add 'Time played today' in 'Your Stats' in the start screen.
* Add daily and weekly targets in the to-be-made settings page.
* Daily target could be a progress bar

**Comment by 4skinSkywalker** [comment]
The daily progress bar is a good idea!

**Comment by 4skinSkywalker** [comment]
![image](https://github.com/user-attachments/assets/743aac85-329c-437d-a318-727535c963f2)
